---
abstract: 'Barfing content to output file.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  Digest: 0
  English: 0
  ExtUtils::MakeMaker: 6.42
  File::Object: 0.01
  File::Slurp: 0
  File::Temp: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Barf
no_index:
  directory:
    - inc
    - t
requires:
  Error::Pure: 0.01
  Exporter: 0
  Readonly: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
  repository:
    type: git
    url: git://github.com/tupinek/IO-Barf
    web: https://github.com/tupinek/IO-Barf
version: 0.01
